# MySQL. Versions 5.5.8 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ajax_app_development

test:
  <<: *default
  database: ajax_app_test

production:
  <<: *default
  database: ajax_app_production
  username: ajax_app
  password: <%= ENV['FIRST_APP_DATABASE_PASSWORD'] %>
